# Generated by Django 5.0.14 on 2026-02-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
