# Generated by Django 5.0.14 on 2026-02-17 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
